apiVersion: v1
kind: Secret
metadata:
  name: quirehut-sts-secrets
type: kubernetes.io/basic-auth
stringData:
  username: "admin-user"
  password: "admin-user-password"

---

apiVersion: v1
kind: Secret
metadata:
  name: quirehut-sts-db-secrets
type: kubernetes.io/basic-auth
stringData:
  username: "quirehut-sts-db-user"
  password: "quirehut-sts-db-password"
  
---

apiVersion: v1
kind: Secret
metadata:
  name: quirehut-sts-db
stringData:
  database: "quirehut-sts-db"