apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quirehut-sts
  labels:
    app: quirehut-sts
    release: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: quirehut-sts
  endpoints:
    - port: http
      path: /metrics
      interval: 30s